/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DiscordWebhookUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MercadoPublicoApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramChatId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TenderTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}